# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d1a2da79951bb388571193baab1022ad4db44f8da43bb26d66d969975606e417d88b67e3ed5dde5585ec5184248b63eb2941b9dbe4e8f72dd3752908b96bfae

test:
  secret_key_base: dd22edd44f11208f7b725b2db6f5cc7240a8cca1f64da6fa4dc6a67a541d7223085a250f4f8e010921583077f8183c69d7b8e170c44c3d37b297dbdcf5039c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
